### PR TITLE
adding colors as input params and example with use of forms arg

### PR DESCRIPTION
**Pull request by PatrickRWright**

### CODE REVIEW

**Comment by aghaynes** [comment]
your map looks odd...there should only be variables that are present in at least two forms shown... i.e. all nodes should have at least two connections... most of the variables in your map seem to be linked to only a single form...

**Comment by aghaynes** [comment]
I just cloned your repo and see a completely different map...
image
The figures in the readme should be consistent with what the code produces...

**Comment by PatrickRWright** [comment]
That is true. I didn't think about that at the time because I was moving the map around manually. Maybe we can show the map produced by the code (for the ctu05 dataset) and then add the manually edited image underneath with a comment stating that it can be moved around by hand. What do you think?

**Comment by aghaynes** [comment]
That's fine. I think that a comment about moving the map around is already there though. We could also mention that igraph allows for different clustering methods (e.g. this 
image
)

Any idea why there seem to be nodes with only single connections in your map?

**Comment by PatrickRWright** [comment]
Maybe we can set the clustering methods as optional argument then too just like the colors. 

The manually edited map could be linked instead of shown in the comment refering to the interactive nature of the graph.

Single connections are - I think - if a variable only appears in a single form. Also for my map I created a subset of the forms using the "^ctu05" regex.

**Comment by aghaynes** [comment]
As it's only exploratory, I would leave the optional argument away as you can change it in the graph plot window under layout.

Single connections shouldn't be shown at all... there's a filter which removes variables that are only seen once...

**Comment by aghaynes** [comment]
maybe change the colours so that they are colour blind compatible... RColorBrewer or http://colorbrewer2.org has a range of palettes. Perhaps #d8b365 (a light brown) and #5ab4ac (+/- turquoise) would be suitable. It should be easy to read the labels over them both at least.

**Pull request merged**
