### PR TITLE
Plot recruitment

### PR DESCRIPTION
**Pull request by PatrickRWright**
Plot recruitment over time for a given export. Pretty straight forward but potentially quite useful.

### CODE REVIEW

**Comment by PatrickRWright** [comment]
@nicoleb7 pointed out that splitting by centres may be useful too, so I will add this. Please don't merge it yet.

**Comment by aghaynes** [comment]
personally, I would turn off the box around the legend... but that's personal preference...

**Comment by PatrickRWright** [comment]
Good suggestions. I will change it.

**Comment by PatrickRWright** [comment]
Unfortunately the example plot for CTU05 doesn't look too impressive, but if you have a look one a real dataset its actually quite nice.

**Comment by PatrickRWright** [comment]
There are a few more small things I would like to adjust. I will point out when the PR is done.

**Comment by PatrickRWright** [comment]
Ok, its ready to be merged unless anyone has any further objections.

**Comment by PatrickRWright** [comment]
For the record: I made some manual checks with local data sets in the AdminTool and the numbers per centre were all equal as expected.

**Comment by aghaynes** [comment]
One other comment... you strip away the Basel specific way of indicating the project, right? Other sites might/do use other ways (e.g. Bern uses XXX - Site name, where XXX is the project number)... maybe it's worth to allow the user to specify either a function or specify a string that is removed via gsub...

**Comment by aghaynes** [comment]
Another thought... Does it make sense to (optionally?) extend the x-axis to "today"?

**Pull request merged**
