### PR TITLE
Retain labels after subset_secuTrial()

### LINKED ISSUE #197: The "tag" of the linked test needs to be corrected.
https://github.com/SwissClinicalTrialOrganisation/secuTrialR/blob/5be910e8a6eba1b8ccfdeb87a6e8cab1d00e9623/tests/testthat/test-read_export_options.R#L126

### LINKED ISSUE #203: label seems to get "lost" in the secuTrialdata object after subsetting
**Describe the bug**
After subsetting a `secuTrialdata` object the variable labels seems to be dropped

**To Reproduce**
Read a secuTrial export. Subset it and check the labels.

**Expected behavior**
Retain variables.

### PR DESCRIPTION
**Pull request by PatrickRWright**
closes #203 

also unrelated small docu fix:
closes #197

### CODE REVIEW

**Comment by PatrickRWright** [comment]
Ready to go from my side.

**Comment by aghaynes** [comment]
thats certainly the simplest approach, but what if someone changes the labels before subsetting, or adds and labels a new variable? Those changes wouldn't be carried through to the new dataset... is it possible it table the labels from the old data and apply them to the new data?

**Comment by PatrickRWright** [comment]
I see what you mean. However, I think that the secuTrialdata object should be used as a raw data archive and wouldn't suggest editing the labels or anything else within... That's an opinion of course. We could add a message if a labelled secuTrialdata object is being subsetted.
e.g. "If you implemented custom labels these are lost during the subsetting process."

**Comment by aghaynes** [comment]
fair enough.

> We could add a message if a labelled secuTrialdata object is being subsetted.
e.g. "If you implemented custom labels these are lost during the subsetting process."

Could go further and only return it if there are variables not listed in the metadata...

While you're working on this, can you check whether the labels exist after the as.data.frame method? Dont know if we ever checked that...

**Comment by PatrickRWright** [comment]
Looks like it works as expected:
``` r
> sT_export <- read_secuTrial(data_dir = export_location)
Read export successfully.
The following export options deviate from the suggested specifications:
Data from hidden fields is part of the export.

> as.data.frame(sT_export, envir = .GlobalEnv)
> sT_export$ctu05treatment$rando_treatment
 [1] "Verum"   "Placebo" "Placebo" "Placebo" "Verum"   "Placebo" "Verum"   "Placebo" "Placebo" "Placebo" "Placebo"
attr(,"label")
[1] "Randomization"
> ctu05treatment$rando_treatment
 [1] "Verum"   "Placebo" "Placebo" "Placebo" "Verum"   "Placebo" "Verum"   "Placebo" "Placebo" "Placebo" "Placebo"
attr(,"label")
[1] "Randomization"
```

**Comment by PatrickRWright** [comment]
> Could go further and only return it if there are variables not listed in the metadata...
I don't quite understand what you mean here.

**Comment by aghaynes** [comment]
I was thinking in the case of a new variable having been added and labelled.... then you could check for any variables not in the metadata, but that wouldn't work for labels that had been changed. Probably easier to just do it as you have...

**Comment by PatrickRWright** [comment]
Ok, so I guess we're good?

Side note: Is there a way to make an object in R "read only"?

**Comment by aghaynes** [comment]
>Ok, so I guess we're good?

 yes, I think so, I'll accept it formally in a review

> Side note: Is there a way to make an object in R "read only"?

Not that I know of... probably not a very desirable trait.... would stop you doing anything to the data... there's almost always stuff to be calculated/derived etc... why do you ask?

**Review by aghaynes — APPROVED** [review]

**Comment by PatrickRWright** [comment]
>Not that I know of... probably not a very desirable trait.... would stop you doing anything to the data... there's almost always stuff to be calculated/derived etc... why do you ask?

That way you could prevent people from changing the `secuTrialdata` object. I googled a bit and it doesn't seem to be a thing.

Can you merge?

**Pull request merged**
