### PR TITLE
add launch_dashboard

### LINKED ISSUE #140: launch_dashboard()
**Is your feature request related to a problem? Please describe.**
No Problem, just convenience.

**Describe the solution you'd like**
`launch_dashboard()` should start the secuTrialR shiny dashboard. Allow supplying `colorscheme` argument to define color style. e.g. reds, mint...

### PR DESCRIPTION
**Pull request by aghaynes**
closes #140 
pkgdown site still needs building

### CODE REVIEW

**Comment by PatrickRWright** [comment]
Right now I'm not really sure whether we want to have this in the package before we release 1.0 since the dashboard is still a bit experimental and needs quite some work. At this point I think taking the shiny thing out for the CRAN release may be better.

**Comment by aghaynes** [comment]
what do we do with this then? we can close it without pulling, but I occasionally delete my fork and make a new one so that everything is fresh. If I do that, then it's lost...

**Comment by markomi** [comment]
@PatrickRWright and I just talked about this and agreed that the entire shiny app is too preliminary to have it on CRAN at this point. At this point, we think it's best to make a separate package just for the shiny app. Pros of this approach:
- one can manage dependancy of the shiny app on an arbitrary version of secuTrialR. We've seen incompatibilities due to poor sync in development between the two
- users can convieniently install the shiny app package and use its module functions as a basis for their own shiny apps that include some of our modules in addition to their own modules
- we can have a separate issue tracking, which will bring some clarity
- we can add supporting functions to the shiny app package and write unit tests, as we usually do
Cons:
- we have two packages to manage
To consider:
- the two packages need to point to and advertise each other, e.g. via readme and the vignette

**Comment by aghaynes** [comment]
That sounds fair enough. I'll just close this PR then and not worry about loosing anything.

**Comment by PatrickRWright** [comment]
I'll close the Issue with the launch_dashboard too.

**Pull request closed without merging**
