### PR TITLE
Remove description check for language specification

### LINKED ISSUE #102: Language parsing does not work if no Export description was specified
**Describe the bug**
`read_secuTrial()` will wrongly return 

`Your export language is not supported and can not be processed.`

if Description has been left empty in the ExportSearchTool.

**To Reproduce**
Create an export without Description and try to read it with `read_secuTrial()`.

**Expected behavior**
Allow to read an export without Description.

**Additional context**
Probably just need to add description [here](https://github.com/SwissClinicalTrialOrganisation/secuTrialR/blob/master/R/internals.R#L145).

### PR DESCRIPTION
**Pull request by PatrickRWright**
Small change but vital.

closes #102

### CODE REVIEW

**Comment by aghaynes** [comment]
Any chance to address #105 here too?

**Comment by PatrickRWright** [comment]
I think its a different type of issue, so I think I will look at this at a later time together with #103 and maybe #103 and #67

**Comment by aghaynes** [comment]
I guess you mean #102, #103, #105, and #67? Sounds fair enough to me...

**Comment by PatrickRWright** [comment]
#105 yes.

**Pull request merged**
