### PR TITLE
adding return_scores function

### PR DESCRIPTION
**Pull request by PatrickRWright**
This function returns all score items, which is a useful utility since they should be recalculated in R previous to analysis.

### CODE REVIEW

**Comment by aghaynes** [comment]
Can you be a bit clearer about the meaning of add_id_name in the help file... I find it a bit cryptic...

**Comment by aghaynes** [comment]
better idea... replace it with `...` and say options passed to read_secuTrial_export

**Comment by PatrickRWright** [comment]
Does this work better?

Properly loading a secuTrial export is critically dependent on the "Add-ID" being available in the export. Standard formats for this ID are "Add-ID", "Zus-ID", "Patient-ID". It is, however, also possible to set a custom "Add-ID" in the secuTrial AdminTool "Design" setting (e.g. "Hospital case ID"). In such a case you will need to set this parameters to what has been defined in the AdminTool.

**Comment by aghaynes** [comment]
I'd just use the `...` notation. You already described it on the read_secutrial_export page...

**Comment by aghaynes** [comment]
Can you add a test for the new option to read_secuTrial? I'm not 100% sure, but I think you got the syntax wrong still... I think it should be `read_secuTrial_export(data_dir = data_dir, ...)` instead of `read_secuTrial_export(data_dir = data_dir, add_id_name = ...)`. 

Another useful thing with `...` is that it allow you to also specify which tables you want in this case, as you can pass any arguments. (also worth testing?)

**Comment by aghaynes** [comment]
The issue you were having with grep... you can get around that by using `object[[x]]` instead of `object[x]`
`curr_items <- x[[x$export_options$meta_names$items]]`
instead of 
`curr_items <- data.frame(x[x$export_options$meta_names$items])`
on line 23 of return_scores.R

**Comment by aghaynes** [comment]
line 69 of read_secutrial_export - `if (name == "casenodes" | name == "cn") {` I would suggest to reference the export options meta_names object. Fewer places to change it if it iAS change something later...

**Pull request merged**
