### PR TITLE
Export to other formats

### PR DESCRIPTION
**Pull request by aghaynes**
Only stata output has been checked (factors ok, dates ok, labels ok)

### CODE REVIEW

**Comment by PatrickRWright** [comment]
Off the top of my head I was wondering if it makes sense to load the written data again with `haven` and compare it to the source that was used to write. I can write the tests if you agree that this is useful.

[ref](https://cran.r-project.org/web/packages/AMR/vignettes/SPSS.html#import-data-from-spsssasstata)

**Comment by aghaynes** [comment]
Possibly... I hadn't considered that at all...

**Comment by PatrickRWright** [comment]
Ok, I will look into that. Probably interesting to learn about `haven` anyway.

**Comment by aghaynes** [comment]
Thanks. Haven is very handy for reading data from other formats. I use it for passing data between Stata and R (mostly in that direction) quite often

**Comment by PatrickRWright** [comment]
@aghaynes loading the written xpt files seems to create some error. See commented lines down at the bottom of the test. Any ideas?

**Comment by aghaynes** [comment]
just for documentation sake... haven::write_xpt limits variable names to 8 characters by default. we can use version 8 though to get around that (32 characters)

**Comment by PatrickRWright** [comment]
> just for documentation sake... haven::write_xpt limits variable names to 8 characters by default. we can use version 8 though to get around that (32 characters)

Unfortunately this did not work.

**Pull request merged**
