### PR TITLE
github actions

### PR DESCRIPTION
**Pull request by aghaynes**
add GH actions for pkgdown and builds

### CODE REVIEW

**Comment by PatrickRWright** [comment]
Thanks @aghaynes 
Out of interest: What exactly is it checking and can be also incorporate it to check the package build like Travis and AppVeyor are doing?

**Comment by aghaynes** [comment]
Far as I can tell, it does do that. I dont know why it's not already automatically running here... I guess because it's not "my" repo... I've just integrated it into presize and it's running... have a look at the last build https://github.com/aghaynes/presize
For the time being I've left appveyor and travis there too...

**Comment by PatrickRWright** [comment]
Where did you configure it? I can activate it here too.

**Comment by aghaynes** [comment]
i just pushed it and it worked...

**Comment by aghaynes** [comment]
it's probably because i'm not the "owner"...

**Comment by PatrickRWright** [comment]
> i just pushed it and it worked...

I don't quite understand.

**Comment by aghaynes** [comment]
> 
> 
> > i just pushed it and it worked...
> 
> I don't quite understand.

I didnt have to do anything at all. I added the code on my local clone, pushed it into my fork of presize and it just worked. It ran all of the tests. I didn't have to do anything else. But I'm an "owner" of that repo, which I'm not for secuTrialR...

**Comment by aghaynes** [comment]
The only thing I did have to do was change the branch used for the github pages site. By default, the pkgdown action will save it to a "gh-pages" branches

**Pull request merged**
