### PR TITLE
Adapt file_tag to new structure of ExportOptions.html

### PR DESCRIPTION
**Pull request by sgrieder**
New version of secuTrial (6.1.2.5 - 6.3.2.5) include language tag in filename of ExportOptions. file_tag was assumed to be identical for table names and ExportOptions. Correct code to remove language tag from file tag.

### CODE REVIEW

**Comment by aghaynes** [comment]
Thanks for this @sgrieder! 
Can you do 3 things for me? 1) change the version number to 1.0.10 in the description file, 2) add yourself as role = ctb also in the description file, and 3) add a news item with a brief description of the change.

**Comment by sgrieder** [comment]
Hi Alan


Thank you, I did the changes and created a pull request. Strangely, all checks have failed now (although I did not change anything else than the description and news file... Any ideas what might be wrong?


Best,

Silvia

________________________________
Von: Alan Haynes ***@***.***>
Gesendet: Donnerstag, 7. April 2022 09:44:37
An: SwissClinicalTrialOrganisation/secuTrialR
Cc: Silvia Grieder; Mention
Betreff: Re: [SwissClinicalTrialOrganisation/secuTrialR] Adapt file_tag to new structure of ExportOptions.html (PR #244)


Thanks for this @sgrieder<https://github.com/sgrieder>!
Can you do 3 things for me? 1) change the version number to 1.0.10 in the description file, 2) add yourself as role = ctb also in the description file, and 3) add a news item with a brief description of the change.

**Comment by aghaynes** [comment]
Hi Silvia, 

Thanks, but can you make them in the same PR? You need to modify your master fork of the repo (you made a new branch called patch-1 with these other changes).

The tests show all failed because the ubuntu ones didn't run. They can't anymore - github no longer has runners with ubuntu 16.04. I updated the workflows to use 20.04, so when you add the description changes to your master fork, the tests should run OK.

Thanks!

**Comment by aghaynes** [comment]
thanks @sgrieder

**Pull request merged**
