### PR TITLE
add sort argument and implementation

### LINKED ISSUE #152: Would be cool if visit plot could be sorted by visit
**Is your feature request related to a problem? Please describe.**
not really, just an inconvenience

**Describe the solution you'd like**
sort forms by first visit they occur

**Describe alternatives you've considered**
none

**Additional context**

### PR DESCRIPTION
**Pull request by gillesdutilh**
closes #152

### CODE REVIEW

**Comment by PatrickRWright** [comment]
@aghaynes can you review this?

**Comment by aghaynes** [comment]
thanks for looking at this @gillesdutilh. Can you move the changes to the visit_structure function instead? That prepares the data for plotting, the plot method only plots...

**Comment by PatrickRWright** [comment]
The version number should now be incremented to 0.8.5

**Comment by PatrickRWright** [comment]
Thank you for the contribution @gillesdutilh 
I will leave to merge to you @aghaynes

**Comment by aghaynes** [comment]
Thanks for looking into this @gillesdutilh. To be honest though, I think that the output from this depends heavily on the setup of the database... for instance, here's the output from a database I have access too...
Unsorted:
image
Sorted:
image

I don't really find the sorted version any more helpful than the other. Having said that, I'm not going to reject your work just because it doesn't work for this database - i'm sure there's others where it will work.

**Comment by gillesdutilh** [comment]
Haha, I agree, your unsorted piece of art is much more expressive! However, I am actually happy to see that I understand your sorted picture much more quickly than the unsorted picture. It depends on whether you want the overview of what happens when over the entire study (then, sorted makes sense) or if you want to focus on groups of related forms  (then the non-sorted version makes sense).

**Pull request merged**
