### PR TITLE
Skip param val ovv

### LINKED ISSUE #212: read_validation_overview() fails to propperly read current validation reports
**Describe the bug**
Seems like a recent secuTrial update changed the amount of lines before the data in the Excel file. Skipping 7 lines
removed the header.

**To Reproduce**
Export a validation report in secuTrial 5.6.2.2 and try and read it with `read_validation_overview()`

**Expected behavior**
Keep header.

### PR DESCRIPTION
**Pull request by PatrickRWright**
closes #212

### CODE REVIEW

**Comment by aghaynes** [comment]
maybe you can read the number of rows dynamically by importing the whole sheet (or the the first 20 lines) and looking of something that indicates the header (e.g. first non-missing in 5th variable?)?

**Comment by PatrickRWright** [comment]
Good idea and likely more stable. I'll give it a go.

**Comment by PatrickRWright** [comment]
Unfortunately I don't see a fixed structure that we can consistently rely on (the file can be customized before exporting it an strictly speaking remains a validation report), which makes the `skip` solution the best one I can currently see.

**Comment by aghaynes** [comment]
shame. are you done then?

**Comment by PatrickRWright** [comment]
yep and thanks for the suggestion.

**Comment by aghaynes** [comment]
One thing... maybe it makes sense to add some extra info into the help file about when you might need it? (just saying that the reports can be customized, etc)

**Comment by PatrickRWright** [comment]
correct

**Pull request merged**
