### PR TITLE
Add language support

### PR DESCRIPTION
**Pull request by markomi**
Test datasets for de/es/it/pl/fr/en added with various export options.
Supported languages are en/de/fr/it/es and not pl.
Dictionaries for different languages added in inst/extdata/dictionaries.
Ensured correct parsing of dates with different languages.
Ensured data is loaded for all supported export languages.

### CODE REVIEW

**Comment by PatrickRWright** [comment]
Thank you @markomi looks good to me. I will leave the merge to @aghaynes incase he would like to have a look over your work.

**Comment by aghaynes** [comment]
Can you add tests for the other languages too? You've tested that german is identified, but not the others...

**Comment by markomi** [comment]
So for now I have them indirectly tested [here](https://github.com/markomi/secuTrialR/blob/28e38e60f29491289445009b954bc5f6fb21d695/tests/testthat/test-read_export_options_languages.R#L63). But it's a good idea to [extend these too](https://github.com/markomi/secuTrialR/blob/28e38e60f29491289445009b954bc5f6fb21d695/tests/testthat/test-internal_functions.R#L149). Will do it first thing tomorrow.

**Comment by aghaynes** [comment]
I kinda feel like read_secutrial_export should still work, but not dates, factorize etc. That way the user can still import there data and work with it, but would have to figure out factors and dates etc on their own...
I don't think that there's anything that would prevent reading the data into R, is there?

**Comment by markomi** [comment]
Hm could be a nice feature.

If we are to allow loading of unsupported languages, we could warn + write NA for language-dependent export options (like for example column names). Is this kind of what you had in mind?

Would you want it implemented in this pull request, or shall we add an issue and put it on our to-do?

**Comment by aghaynes** [comment]
I think it would be good to have in this PR. 

It's probably enough to put an if loop in dates and factorize so that it only runs the parts that actually do stuff if the language is supported...

Do you think you can implement it?

**Comment by markomi** [comment]
Sounds good to me! I'll add it.

**Comment by markomi** [comment]
@aghaynes 
I have extended the list of languages supported by secuTrialR to include the polish language. Thus, secuTrialR can now handle exports made in any language currently available in secuTrial. Could you please review once the build is completed?

A language-independent import will need a bit more work, since is_rectangular and column_names variables are used in read_secuTrial_export(). I can open a new feature request for this.

**Comment by PatrickRWright** [comment]
For me its fine. Thank you @markomi

**Comment by aghaynes** [comment]
minor comment...in dates, factorize and labels you still extract the language from the export options...is that necessary?

**Comment by PatrickRWright** [comment]
would you rather extract them like this?
``` r
d$export_options$dict_items$lang
```
Since dict_items is now part of the export_options a final change may actually be to remove export_options$lang then?

**Pull request merged**
