### PR TITLE
Functions for form status statistics

### LINKED ISSUE #42: plot form completeness/availability
For each form, plot percentage of completeness.

This is similar/related to assess_form_variable_completeness

### LINKED ISSUE #49: assess_form_variable_completeness issue
assess_form_variable_completeness will not work correctly with the CTU05 dataset if completeness is set to "allforms". This is because that CDMA has treatment arms and variables in forms that are hidden depending on the visit. Both violate assumptions that are being made within the "allforms" branch.

Likely, "allforms" will only be a viable option for very rigid CDMAs.

### LINKED ISSUE #53: add some of the interval type variables into the CTU05 dataset?

### PR DESCRIPTION
**Pull request by PatrickRWright**
This PR adds the functions `form_status_counts` and `form_status_summary`. The latter wraps the prior. The overall aim is to get an informed overview of how complete the data in the secuTrial export of interest is.

I will implement a further example CDMA with warnings and errors (currently not in the example data). I have checked on local private data though and everything seems to work.

Maybe you two can take the functions for a quick spin with some of you data and report if it works and what you think. @aghaynes @markomi 

I have also soft deprecated `assess_form_variable_completeness` for now, since it makes too many assumptions.

Issues resolved:
closes #53 
closes #49 
closes #42 (its not a plot but a table)

### CODE REVIEW

**Comment by PatrickRWright** [comment]
I just realized that this is currently limited to English language exports so please don't merge yet. I will probably need to include a dictionary.

**Comment by aghaynes** [comment]
Would be good to add something to readme about this, as well as the vignette

**Comment by PatrickRWright** [comment]
I will write something up. Anything specific you would like me to add?

**Comment by aghaynes** [comment]
Can you make sure that the demo in the readme works? It currently gives an error...

**Comment by PatrickRWright** [comment]
Good catch. I didn't see that you were also using ctu05 in the fold down. The functions need factorized input. It should work now.

**Comment by PatrickRWright** [comment]
I'm not sure I agree with your comment or maybe I don't quite understand. Just to clarify `form_count` is the amount of a specific form type which has been saved in the export you are looking at. Actually its the row sum of partly_filled, completely_filled and empty.

**Comment by markomi** [comment]
> I'm not sure I agree with your comment or maybe I don't quite understand. Just to clarify `form_count` is the amount of a specific form type which has been saved in the export you are looking at. Actually its the row sum of partly_filled, completely_filled and empty.

True! Sorry my bad.

**Pull request merged**
