### PR TITLE
Add support for durations (calculated intervals)

### PR DESCRIPTION
**Pull request by aghaynes**

### CODE REVIEW

**Comment by aghaynes** [comment]
related to #37

**Comment by PatrickRWright** [comment]
I will wait with the merge here until I have set up a test CDMA which includes durations.

**Comment by aghaynes** [comment]
ok. minor changes might also be necessary for write_secutrial too (to change the appended names),  once that branch's been merged

**Comment by PatrickRWright** [comment]
Is this ready for review or are you still working on it?

**Comment by aghaynes** [comment]
this is what the new dataset is for... i will add some tests using it

**Comment by PatrickRWright** [comment]
Oh, whoops I must have kind of missed looking at the timeline.

**Comment by PatrickRWright** [comment]
@aghaynes can you add an example for the documentation of durations_secutrial.R?
Also I suggest to reword "strange" to something like "uncommon" in the README.

**Comment by aghaynes** [comment]
Closing. There are too many assumptions leading to incorrect data. Better not to support this. 

The salvageable stuff will be moved to a new PR.

**Pull request closed without merging**
